apiVersion: v1
kind: ConfigMap
metadata:
  name: mynamespace
  namespace: $NAMESPACE
data:
  namespace: $NAMESPACE 

---

kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
  namespace: $NAMESPACE
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: $NODEPORT

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: train-schedule-deployment
  namespace: $NAMESPACE
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: $MYIMAGE
        env:
        # Define the environment variable
        - name: NAMESPACE
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: mynamespace
              # Specify the key associated with the value
              key: namespace
        ports:
        - containerPort: 8080
