apiVersion: v1
kind: Service
metadata:
  name: train-schedule-service
spec:
  type: NodePort
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30008

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      imagePullSecrets:
      - name: aws-ecr-hello-go
      containers:
      - name: train-schedule
        image: 635117535044.dkr.ecr.us-east-1.amazonaws.com/trains:$BUILD_NUMBER
        ports:
        - containerPort: 8080
