kind: Service
apiVersion: v1
metadata:
  name: train-schedule-service
spec:
  selector:
    app: train-schedule
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 9376
  clusterIP:
  loadBalancerIP: 172.31.104.217
  type: LoadBalancer
 

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: train-schedule-deployment
  labels:
    app: train-schedule
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train-schedule
  template:
    metadata:
      labels:
        app: train-schedule
    spec:
      containers:
      - name: train-schedule
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
